// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Model
{
    [default_interface]
    runtimeclass ColorScheme
    {
        ColorScheme();
        ColorScheme(String name, UInt32 defaultFg, UInt32 defaultBg, UInt32 cursorColor);

        String Name;

        UInt32 Foreground;
        UInt32 Background;
        UInt32 SelectionBackground;
        UInt32 CursorColor;

        // TODO CARLOS: Tables!
        //UInt32[] Table;
    }
}
